version: '2.2' 
services:
  nginxproxymanager:
    image: 'jc21/nginx-proxy-manager:latest' 
    container_name: nginxproxymanager
    restart: unless-stopped 
    ports:
      - '80:80'
      - '81:81'
      - '443:443' 
    volumes:
      - /home/rezo/nginx/data:/data
      - /home/rezo/nginx/letsencrypt:/etc/letsencrypt 

  nextcloud:
    image: lscr.io/linuxserver/nextcloud:latest
    container_name: nextcloud
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=US/Central 
    volumes:
      - /home/rezo/nextcloud/appdata:/config 
      - /home/rezo/nextcloud/data:/data
    restart: unless-stopped
    networks:
      - nextcloud
      - default
  
  nextcloud-db:
    image: postgres:latest
    container_name: nextcloud-db
    volumes:
      - ./nextcloud/db/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD="${POSTGRES_PASSWORD}"
      - POSTGRES_USER="${POSTGRES_USER}"
    networks:
      - nextcloud

  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:latest
    container_name: audiobookshelf
    volumes:
      - /home/rezo/audiobookshelf/config:/config
      - /home/rezo/audiobookshelf/metadata:/metadata
      - /mnt/trashnas/Media_Library/Books:/audiobooks
      # - /mnt/trashnas/Media_Library/podcasts:/podcasts

  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin 
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=US/Central 
    volumes:
      - /home/rezo/jellyfin/config:/config
      - /home/rezo/jellyfin/cache:/cache
      - /home/rezo/jellyfin/data:/data
      - type: bind
        source: /mnt/trashnas/Jellyfin_Cache
        target: /transcode
      - type: bind
        source: /mnt/trashnas/Media_Library/Shows
        target: /data/tvshows
      - type: bind
        source: /mnt/trashnas/Media_Library/Movies
        target: /data/movies 
      - type: bind
        source: /mnt/trashnas/Media_Library/Music
        target: /data/music
    ports:
      - '8920:8920'
      - '8096:8096'
    restart: unless-stopped

  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - /home/rezo/homeassistant/config:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    restart: unless-stopped
    privileged: true
    network_mode: host
    # networks:
    #   - intermediate
    #   - default
  crafty:
    container_name: crafty_container
    image: "registry.gitlab.com/crafty-controller/crafty-4:latest"
    restart: always
    network_mode: host
    environment:
      - TZ=America/Chicago
    ports:
      - '8011:8001' # HTTP
      - '8455:8444' # HTTPS
      # - "8123:8123" # DYNMAP
      # - "19132:19132/udp" # BEDROCK
      - "25500-25600:25500-25600" # MC SERV PORT RANGE
    volumes:
      - /home/rezo/crafty/backups:/crafty/backups
      - /home/rezo/crafty/logs:/crafty/logs
      - /home/rezo/crafty/servers:/crafty/servers
      - /home/rezo/crafty/config:/crafty/app/config
      - /home/rezo/crafty/import:/crafty/import
networks:
  nextcloud:
  intermediate:
    driver: macvlan
    ipam:
      config:
        - subnet: 192.168.0.0/16
          ip_range: 192.168.0.128/27
          gateway: 192.168.1.1
    driver_opts:
      parent: enp1s0f0
      
